apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: example-configmap
    literals:
      - SQLITE_DB_LOCATION=/tmp/todos/todo.db
resources:
  - deployment.yaml
